"""Initial schema

Revision ID: 1e63b3614d59
Revises: 
Create Date: 2026-06-16 06:40:11.265720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e63b3614d59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('health_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nama_guest', sa.String(length=100), nullable=True),
    sa.Column('berat_badan', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tinggi_badan', sa.SmallInteger(), nullable=False),
    sa.Column('umur', sa.SmallInteger(), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=False),
    sa.Column('aktivitas', sa.Enum('sedentary', 'lightly', 'moderately', 'very', 'extra'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('berat_badan', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kalori_aktual', sa.SmallInteger(), nullable=True),
    sa.Column('target_kalori', sa.SmallInteger(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('status_bmi', sa.String(length=20), nullable=False),
    sa.Column('kalori_tdee', sa.SmallInteger(), nullable=False),
    sa.Column('kalori_fuzzy', sa.SmallInteger(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('lemak_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('karbo_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('fuzzy_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('progress_logs')
    op.drop_table('health_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
